KennelCheckin.MVC/Controllers/Data/DogBasicController.cs
using Kennel.Models.Data.DogBasic;
using Kennel.Models.Joining_Data.DogInfo;
using Kennel.Service.Data;
using Kennel.Service.Joining;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace KennelCheckin.MVC.Controllers.Data
{
    [Authorize(Roles = "Owner,Admin")]
    public class DogBasicController : Controller
    {
        private DogBasicService CreateDogBasicService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var dogBasicService = new DogBasicService(userId);
            return dogBasicService;
        }

        private DogInfoService CreateDogInfoService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var dogInfoService = new DogInfoService(userId);
            return dogInfoService;
        }

        //Add method here VVVV
        //GET
        public async Task<ActionResult> Create()
        {
            DogBasicService service = CreateDogBasicService();
            if (await service.CheckOwner())//True if there is no owner set up
            {
                return RedirectToAction("Create", "Owner");
            }
            return View();
        }

        //Add method here VVVV
        //GET
        //public async Task<ActionResult> Details(int id)
        //{
        //    DogBasicService service = CreateDogBasicService();

        //    var model = await service.GetDogBasicById(id);

        //    return View(model);
        //}

        //Add method here VVVV
        //GET
        public async Task<ActionResult> Edit(int id)
        {
            DogBasicService service = CreateDogBasicService();

            var model = await service.GetDogBasicByIdEditable(id);

            return View(model);
        }

        //Add code here vvvv
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(DogBasicCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateDogBasicService();

            if (await service.CreateDogBasic(model))
            {
                DogInfoService infoService = CreateDogInfoService();
                int newDogInfoId = await infoService.CreateDogInfo();
                return RedirectToAction($"Details/{newDogInfoId}", "DogInfo");
            };

            ModelState.AddModelError("", "Dog could not be added");

            return View(model);
        }

        //Add method here VVVV
        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, DogBasicEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateDogBasicService();

            if (await service.UpdateDogBasic(id, model))
            {
                //TempData["SaveResult"] = "Your note was edited.";
                return RedirectToAction("Index", "DogInfo");
            };

            ModelState.AddModelError("", "Dog could not be edited.");

            return View(model);
        }
    }
}

KennelCheckin.MVC/Controllers/Data/MedicationController.cs
using Kennel.Models.Data.Medication;
using Kennel.Models.Joining_Data.DogInfo;
using Kennel.Service.Data;
using Kennel.Service.Joining;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace KennelCheckin.MVC.Controllers.Data
{
    [System.Web.Mvc.Authorize(Roles = "Owner,Admin")]
    public class MedicationController : Controller
    {
        private MedicationService CreateMedicationService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var medicationService = new MedicationService(userId);
            return medicationService;
        }
        private DogInfoService CreateDogInfoService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var dogInfoService = new DogInfoService(userId);
            return dogInfoService;
        }

        //Add method here VVVV
        //GET
        public async Task<ActionResult> Create()
        {
            return View();
        }

        //Add method here VVVV
        //GET
        //public async Task<ActionResult> Details(int id)
        //{
        //    MedicationService service = CreateMedicationService();

        //    var model = await service.GetMedicationById(id);

        //    return View(model);
        //}

        //Add method here VVVV
        //GET
        public async Task<ActionResult> Edit(int id)
        {
            MedicationService service = CreateMedicationService();

            var model = await service.GetMedicationByIdEditable(id);

            return View(model);
        }

        //Add method here VVVV
        //GET
        public async Task<ActionResult> Delete(int id)
        {
            MedicationService service = CreateMedicationService();

            var model = await service.GetMedicationById(id);
            return View(model);
        }

        //Add code here vvvv
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([FromUri] int id, MedicationCreate model)
        {
            if (!ModelState.IsValid || (model.MorningMeal == false && model.EveningMeal == false)) return View(model);

            var service = CreateMedicationService();

            if (await service.CreateMedication(model))
            {
                await service.CreateMedicationToDogInfo(id);
                return RedirectToAction($"Details/{id}", "DogInfo");
            };

            ModelState.AddModelError("", "Medication could not be added");

            return View(model);
        }

        //Add method here VVVV
        [System.Web.Mvc.HttpPost]
        [System.Web.Mvc.ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, MedicationEdit model)
        {
            if (!ModelState.IsValid || (model.MorningMeal == false && model.EveningMeal == false)) return View(model);

            var service = CreateMedicationService();

            if (await service.UpdateMedication(id, model))
            {
                return RedirectToAction("Index", "DogInfo");
            };

            ModelState.AddModelError("", "Medication could not be edited.");

            return View(model);
        }

        [System.Web.Mvc.HttpPost]
        [System.Web.Mvc.ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteMedication(int id)
        {

            var service = CreateMedicationService();

            DogInfoService infoService = CreateDogInfoService();
            if (await service.DeleteMedication(id))
            {
                return RedirectToAction("Index", "DogInfo");
            };

            ModelState.AddModelError("", "Medication could not be deleted.");

            return await Delete(id);
        }
    }
}

KennelCheckin.MVC/Controllers/Data/OwnerController.cs
using Kennel.Models.Data.Owner;
using Kennel.Service.Data;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace KennelCheckin.MVC.Controllers.Data
{
    [System.Web.Mvc.Authorize(Roles = "Owner,Admin")]
    public class OwnerController : Controller
    {
        private OwnerService CreateOwnerService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var ownerService = new OwnerService(userId);
            return ownerService;
        }

        //Add method here VVVV
        //GET
        public async Task<ActionResult> Create()
        {
            OwnerService service = CreateOwnerService();
            if (await service.CheckOwnerExists())//True if there is no owner set up
            {
                return View();
            }
            return RedirectToAction("Index", "DogInfo");
        }

        //Add method here VVVV
        //GET
        public async Task<ActionResult> Details(int id)
        {
            OwnerService service = CreateOwnerService();

            var model = await service.GetOwnerById(id);

            return View(model);
        }

        //Add method here VVVV
        //GET
        public async Task<ActionResult> Edit(int id)
        {
            OwnerService service = CreateOwnerService();

            var model = await service.GetOwnerByIdEditable(id);

            return View(model);
        }

        //Add code here vvvv
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(OwnerCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateOwnerService();

            if (await service.CreateOwner(model))
            {
                //TempData["SaveResult"] = "Your note was created.";
                return RedirectToAction("Index", "DogInfo");
            };

            ModelState.AddModelError("", "Owner information could not be created.");

            return View(model);
        }

        //Add method here VVVV
        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, OwnerEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateOwnerService();

            if (await service.UpdateOwner(id, model))
            {
                //TempData["SaveResult"] = "Your note was edited.";
                return RedirectToAction("Index", "DogInfo");
            };

            ModelState.AddModelError("", "Owner information could not be edited.");

            return View(model);
        }
    }
}

KennelCheckin.MVC/Controllers/Joining Data/DogVisitController.cs
using Kennel.Models.Joining_Data.DogVisit;
using Kennel.Models.Joining_Data.DogInfo;
using Kennel.Service.Data;
using Kennel.Service.Joining;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace KennelCheckin.MVC.Controllers.Joinging_Data
{
    [System.Web.Mvc.Authorize(Roles = "Owner,Admin")]
    public class DogVisitController : Controller
    {
        private DogVisitService CreateDogVisitService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var dogVisitService = new DogVisitService(userId);
            return dogVisitService;
        }
        private DogInfoService CreateDogInfoService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var dogInfoService = new DogInfoService(userId);
            return dogInfoService;
        }

        //Add method here VVVV
        //GET
        public async Task<ActionResult> Create()//ID of the DogInfo
        {
            return View();
        }

        ////Add code here vvvv
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([FromUri] int id, DogVisitCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            if (DateTime.Compare(model.DropOffTime, model.PickUpTime) >= 0)
            {
                ModelState.AddModelError("", "Dropoff date must be before pickup");

                return View(model);
            }

            var service = CreateDogVisitService();

            if (await service.CreateDogVisit(id, model))
            {
                return RedirectToAction($"Index", "DogInfo");
            };

            ModelState.AddModelError("", "DogVisit could not be added");

            return View(model);
        }

        ////Add method here VVVV
        ////GET
        //public async Task<ActionResult> Details(int id)
        //{
        //    DogVisitService service = CreateDogVisitService();

        //    var model = await service.GetDogVisitById(id);

        //    return View(model);
        //}

        ////Add method here VVVV
        ////GET
        public async Task<ActionResult> Edit(int id)
        {
            DogVisitService service = CreateDogVisitService();

            var model = await service.GetDogVisitByIdEditable(id);

            return View(model);
        }

        //Add method here VVVV
        [System.Web.Mvc.HttpPost]
        [System.Web.Mvc.ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, DogVisitEdit model)
        {
            if (!ModelState.IsValid)
            {
                DogVisitService remedialService = CreateDogVisitService();

                var remedialmodel = await remedialService.GetDogVisitByIdEditable(id);

                return View(remedialmodel);
            }


            if (DateTime.Compare(model.DropOffTime, model.PickUpTime) >= 0)
            {
                ModelState.AddModelError("", "Dropoff date must be before pickup");

                return View(model);
            }

            var service = CreateDogVisitService();

            if (await service.UpdateDogVisit(id, model))
            {
                //TempData["SaveResult"] = "Your note was edited.";
                return RedirectToAction("Index", "DogInfo");
            };

            ModelState.AddModelError("", "Dog Visit could not be edited.");

            return View(model);
        }

        ////GET
        public async Task<ActionResult> ChangePickup(int id)
        {
            DogVisitService service = CreateDogVisitService();

            var model = await service.GetDogVisitByIdChangePickup(id);

            return View(model);
        }

        //Add method here VVVV
        [System.Web.Mvc.HttpPost]
        [System.Web.Mvc.ActionName("ChangePickup")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePickup(int id, DogVisitChangePickup model)
        {
                
            DogVisitService service = CreateDogVisitService();

            if (!ModelState.IsValid)
            {
                var original = await service.GetDogVisitByIdChangePickup(id);
                return View(original);
            }

            if (DateTime.Now.Date> model.PickUpTime)
            {
                ModelState.AddModelError("", "New pick-up date must be today or later");

                var original = await service.GetDogVisitByIdChangePickup(id);

                return View(original);
            }
            else if(await service.ChangePickupDogVisit(id, model))
            {
                return RedirectToAction("Index", "DogInfo");
            }
            else
            {
                ModelState.AddModelError("", "Dog Visit could not be edited.");
                var original = await service.GetDogVisitByIdChangePickup(id);
                return View(original);
            }

        }

        ////Add method here VVVV
        ////GET
        public async Task<ActionResult> Delete(int id)
        {
            DogVisitService service = CreateDogVisitService();

            var model = await service.GetDogVisitById(id);
            return View(model);
        }



        [System.Web.Mvc.HttpPost]
        [System.Web.Mvc.ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteDogVisit(int id)
        {

            var service = CreateDogVisitService();

            if (await service.DeleteDogVisit(id))
            {
                return RedirectToAction("Index", "DogInfo");
            };

            ModelState.AddModelError("", "DogVisit could not be deleted.");

            return await Delete(id);
        }

        //=============Helper=======//
        //public async Task<ActionResult> DogNameLookUp(int dogInfoId)
        //{
        //    DogVisitService service = CreateDogVisitService();
        //    var dogName = await service.GetDogName(dogInfoId);
        //    return Content($"{dogName}");
        //}
    }
}

KennelCheckin.MVC/Views/DogInfo/Delete.cshtml
@model Kennel.Models.Data.Joining_Data.DogInfo.DisplayOnly.DogInfoDetails

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to remove @Html.DisplayFor(model => model.DogBasic.DogName)?</h3>
<div>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }

    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

KennelCheckin.MVC/Views/DogInfo/Details.cshtml
@model Kennel.Models.Data.Joining_Data.DogInfo.DisplayOnly.DogInfoDetails

@{
    ViewBag.Title = "Details";
}

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

<div class="row">
    <div class="col-md-8 mx-auto">
        <h2 class="text-center">@Model.DogBasic.DogName Details</h2>
        @if (Model.DogInfo.DogImageId == 0)
        {
            <h4 class="text-center">No Image</h4>
            <p class="text-center">@Html.ActionLink("Add", "Create", "DogImage", new { id = Model.DogInfo.DogInfoId }, null)</p>
        }
        else
        {
            <img class="center-block" src="@Url.Action("RenderPhoto", "DogImage", new { photoId = Model.DogInfo.DogImageId })" width="200" height="200" alt="Pet Image" />
            <p class="text-center">
                @Html.ActionLink("Replace", "Edit", "DogImage", new { id = Model.DogInfo.DogImageId }, null) |
                @Html.ActionLink("Delete", "Delete", "DogImage", new { id = Model.DogInfo.DogImageId }, null)
            </p>
        }
    </div>
</div>

<div class="shadow-lg p-3 mb-5 bg-white rounded">
    <table class="table">
        <tbody>
            <tr>
                <h4>Basics</h4>
                <p>@Html.ActionLink("Edit", "Edit", "DogBasic", new { id = Model.DogBasic.DogBasicId }, null)</p>
            </tr>
            <tr>
                <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.DogBasic.DogName)</th>
                <td class="col-md-2">@Html.DisplayFor(model => model.DogBasic.DogName)</td>
                <td class="col-md-8"></td>
            </tr>
            <tr>
                <th scope="row">@Html.DisplayNameFor(model => model.DogBasic.Breed)</th>
                <td>@Html.DisplayFor(model => model.DogBasic.Breed)</td>
            </tr>
            <tr>
                <th scope="row">@Html.DisplayNameFor(model => model.DogBasic.Weight)</th>
                <td>@Html.DisplayFor(model => model.DogBasic.Weight)</td>
            </tr>
        </tbody>
    </table>
</div>

<div class="shadow-lg p-3 mb-5 bg-white rounded">
    <table class="table">
        <tbody>
            <tr>
                <h4>Food</h4>
                @if (Model.DogInfo.FoodId == 0)
                {
                    <h5>If there is no food entered, your dog will be fed one time a day based on their weight.</h5>
                    <p>@Html.ActionLink("Add", "Create", "Food", new { id = Model.DogInfo.DogInfoId }, null)</p>
                }
                else
                {
                    <p>
                        @Html.ActionLink("Edit", "Edit", "Food", new { id = Model.Food.FoodId }, null) |
                        @Html.ActionLink("Delete", "Delete", "Food", new { id = Model.Food.FoodId }, null)
                    </p>
                }
            </tr>
            @if (Model.DogInfo.FoodId == 0)
            {
            }
            else
            {
                <tr>
                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.Food.Name)</th>
                    <td class="col-md-2">@Html.DisplayFor(model => model.Food.Name)</td>
                    <td class="col-md-8"></td>
                </tr>
                <tr>
                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.Food.AmountPerMeal)</th>
                    <td class="col-md-2">@Html.DisplayFor(model => model.Food.AmountPerMeal)</td>
                    <td class="col-md-8"></td>
                </tr>
                <tr>
                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.Food.MorningMeal)</th>
                    <td class="col-md-2">@Html.DisplayFor(model => model.Food.MorningMeal)</td>
                    <td class="col-md-8"></td>
                </tr>
                <tr>
                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.Food.EveningMeal)</th>
                    <td class="col-md-2">@Html.DisplayFor(model => model.Food.EveningMeal)</td>
                    <td class="col-md-8"></td>
                </tr>

            }
        </tbody>
    </table>
</div>

<div class="shadow-lg p-3 mb-5 bg-white rounded">
    <table class="table">
        <tbody>
            <tr>
                <h4>Special Details</h4>
                @if (Model.DogInfo.SpecialId == 0)
                {
                    <p>@Html.ActionLink("Add", "Create", "Special", new { id = Model.DogInfo.DogInfoId }, null)</p>
                }
                else
                {
                    <p>
                        @Html.ActionLink("Edit", "Edit", "Special", new { id = Model.Special.SpecialId }, null) |
                        @Html.ActionLink("Delete", "Delete", "Special", new { id = Model.Special.SpecialId }, null)
                    </p>
                }
            </tr>
            @if (Model.DogInfo.SpecialId == 0)
            {
            }
            else
            {
                <tr>
                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.Special.Instructions)</th>
                    <td class="col-md-2">@Html.DisplayFor(model => model.Special.Instructions)</td>
                    <td class="col-md-8"></td>
                </tr>
                <tr>
                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.Special.Allergies)</th>
                    <td class="col-md-2">@Html.DisplayFor(model => model.Special.Allergies)</td>
                    <td class="col-md-8"></td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="shadow-lg p-3 mb-5 bg-white rounded">
    <table class="table">
        <tbody>
            <tr>
                <h4>Veterinarian Details</h4>
                @if (Model.DogInfo.VetId == 0)
                {
                    <p>@Html.ActionLink("Add", "Create", "Vet", new { id = Model.DogInfo.DogInfoId }, null)</p>
                }
                else
                {
                    <p>
                        @Html.ActionLink("Edit", "Edit", "Vet", new { id = Model.Vet.VetId }, null) |
                        @Html.ActionLink("Delete", "Delete", "Vet", new { id = Model.Vet.VetId }, null)
                    </p>
                }
            </tr>
            @if (Model.DogInfo.VetId == 0)
            {
            }
            else
            {
                <tr>
                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.Vet.BusinessName)</th>
                    <td class="col-md-2">@Html.DisplayFor(model => model.Vet.BusinessName)</td>
                    <td class="col-md-8"></td>
                </tr>
                <tr>
                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.Vet.VetName)</th>
                    <td class="col-md-2">@Html.DisplayFor(model => model.Vet.VetName)</td>
                    <td class="col-md-8"></td>
                </tr>
                <tr>
                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.Vet.Phone)</th>
                    <td class="col-md-2">@Html.DisplayFor(model => model.Vet.Phone)</td>
                    <td class="col-md-8"></td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="shadow-lg p-3 mb-5 bg-white rounded">
    <table class="table">
        <tbody>
            <tr>
                @if (Model.MedicationList.Count() == 0)
                {
                    <h4>Medication Details</h4>
                    <p>@Html.ActionLink("Add", "Create", "Medication", new { id = Model.DogInfo.DogInfoId }, null)</p>
                }
                else if (Model.MedicationList.Count() == 1)
                {
                    <h4>Medication Details</h4>
                    <p>@Html.ActionLink("Add", "Create", "Medication", new { id = Model.DogInfo.DogInfoId }, null)</p>
                }
                else
                {
                    <h4>Medications Details</h4>
                    <p>@Html.ActionLink("Add", "Create", "Medication", new { id = Model.DogInfo.DogInfoId }, null)</p>
                }
            </tr>
            @if (Model.MedicationList.Count() == 0)
            {
            }
            else
            {
                for (int i = 0; i < Model.MedicationList.Count(); i++)
                {
                        <table class="table">
                            <thead>
                                <tr>
                                    <td></td>
                                </tr>
                                <tr>
                                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.MedicationList.ElementAt(i).Name)</th>
                                    <th class="col-md-2">@Html.DisplayFor(model => model.MedicationList.ElementAt(i).Name)</th>
                                    <td class="col-md-8">
                                            @Html.ActionLink("Edit", "Edit", "Medication", new { id = Model.MedicationList.ElementAt(i).MedicationId }, null) |
                                            @Html.ActionLink("Delete", "Delete", "Medication", new { id = Model.MedicationList.ElementAt(i).MedicationId }, null)
                                    </td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.MedicationList.ElementAt(i).Dose)</th>
                                    <td class="col-md-2">@Html.DisplayFor(model => model.MedicationList.ElementAt(i).Dose)</td>
                                    <td class="col-md-8"></td>
                                </tr>
                                <tr>
                                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.MedicationList.ElementAt(i).MorningMeal)</th>
                                    <td class="col-md-2">@Html.DisplayFor(model => model.MedicationList.ElementAt(i).MorningMeal)</td>
                                    <td class="col-md-8"></td>
                                </tr>
                                <tr>
                                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.MedicationList.ElementAt(i).EveningMeal)</th>
                                    <td class="col-md-2">@Html.DisplayFor(model => model.MedicationList.ElementAt(i).EveningMeal)</td>
                                    <td class="col-md-8"></td>
                                </tr>
                                <tr>
                                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.MedicationList.ElementAt(i).Instructions)</th>
                                    <td class="col-md-2">@Html.DisplayFor(model => model.MedicationList.ElementAt(i).Instructions)</td>
                                    <td class="col-md-8"></td>
                                </tr>
                            </tbody>
                        </table>
                }
            }
            </tbody>
        </table>
    </div>

    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>