KennelCheckin.MVC/Controllers/Joining Data/DogVisitController.cs
using Kennel.Models.Joining_Data.DogVisit;
using Kennel.Models.Joining_Data.DogInfo;
using Kennel.Service.Data;
using Kennel.Service.Joining;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace KennelCheckin.MVC.Controllers.Joinging_Data
{
    [System.Web.Mvc.Authorize(Roles = "Owner,Admin")]
    public class DogVisitController : Controller
    {
        private DogVisitService CreateDogVisitService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var dogVisitService = new DogVisitService(userId);
            return dogVisitService;
        }
        private DogInfoService CreateDogInfoService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var dogInfoService = new DogInfoService(userId);
            return dogInfoService;
        }

        //Add method here VVVV
        //GET
        public async Task<ActionResult> Create()//ID of the DogInfo
        {
            return View();
        }

        ////Add code here vvvv
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([FromUri] int id, DogVisitCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            if (DateTime.Compare(model.DropOffTime, model.PickUpTime) >= 0)
            {
                ModelState.AddModelError("", "Dropoff date must be before pickup");

                return View(model);
            }

            var service = CreateDogVisitService();

            if (await service.CreateDogVisit(id, model))
            {
                return RedirectToAction($"Index", "DogInfo");
            };

            ModelState.AddModelError("", "DogVisit could not be added");

            return View(model);
        }

        ////Add method here VVVV
        ////GET
        //public async Task<ActionResult> Details(int id)
        //{
        //    DogVisitService service = CreateDogVisitService();

        //    var model = await service.GetDogVisitById(id);

        //    return View(model);
        //}

        ////Add method here VVVV
        ////GET
        public async Task<ActionResult> Edit(int id)
        {
            DogVisitService service = CreateDogVisitService();

            var model = await service.GetDogVisitByIdEditable(id);

            return View(model);
        }

        //Add method here VVVV
        [System.Web.Mvc.HttpPost]
        [System.Web.Mvc.ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, DogVisitEdit model)
        {
            if (!ModelState.IsValid)
            {
                DogVisitService remedialService = CreateDogVisitService();

                var remedialmodel = await remedialService.GetDogVisitByIdEditable(id);

                return View(remedialmodel);
            }


            if (DateTime.Compare(model.DropOffTime, model.PickUpTime) >= 0)
            {
                ModelState.AddModelError("", "Dropoff date must be before pickup");

                return View(model);
            }

            var service = CreateDogVisitService();

            if (await service.UpdateDogVisit(id, model))
            {
                //TempData["SaveResult"] = "Your note was edited.";
                return RedirectToAction("Index", "DogInfo");
            };

            ModelState.AddModelError("", "Dog Visit could not be edited.");

            return View(model);
        }

        ////GET
        public async Task<ActionResult> ChangePickup(int id)
        {
            DogVisitService service = CreateDogVisitService();

            var model = await service.GetDogVisitByIdChangePickup(id);

            return View(model);
        }

        //Add method here VVVV
        [System.Web.Mvc.HttpPost]
        [System.Web.Mvc.ActionName("ChangePickup")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePickup(int id, DogVisitChangePickup model)
        {
                
            DogVisitService service = CreateDogVisitService();

            if (!ModelState.IsValid)
            {
                var original = await service.GetDogVisitByIdChangePickup(id);
                return View(original);
            }

            if (DateTime.Now.Date> model.PickUpTime)
            {
                ModelState.AddModelError("", "New pick-up date must be today or later");

                var original = await service.GetDogVisitByIdChangePickup(id);

                return View(original);
            }
            else if(await service.ChangePickupDogVisit(id, model))
            {
                return RedirectToAction("Index", "DogInfo");
            }
            else
            {
                ModelState.AddModelError("", "Dog Visit could not be edited.");
                var original = await service.GetDogVisitByIdChangePickup(id);
                return View(original);
            }

        }

        ////Add method here VVVV
        ////GET
        public async Task<ActionResult> Delete(int id)
        {
            DogVisitService service = CreateDogVisitService();

            var model = await service.GetDogVisitById(id);
            return View(model);
        }



        [System.Web.Mvc.HttpPost]
        [System.Web.Mvc.ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteDogVisit(int id)
        {

            var service = CreateDogVisitService();

            if (await service.DeleteDogVisit(id))
            {
                return RedirectToAction("Index", "DogInfo");
            };

            ModelState.AddModelError("", "DogVisit could not be deleted.");

            return await Delete(id);
        }

        //=============Helper=======//
        //public async Task<ActionResult> DogNameLookUp(int dogInfoId)
        //{
        //    DogVisitService service = CreateDogVisitService();
        //    var dogName = await service.GetDogName(dogInfoId);
        //    return Content($"{dogName}");
        //}
    }
}

KennelCheckin.MVC/Controllers/KennelControllers/KennelController.cs
using Kennel.Models.Data.Kennel.KennelDashboardItems;
using Kennel.Service.Joining;
using Kennel.Service.Kennel;
using KennelData.Data;
using KennelData.JoiningData;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace KennelCheckin.MVC.Controllers.KennelControllers
{
    [System.Web.Mvc.Authorize(Roles = "Admin,Worker")]
    public class KennelController : Controller
    {
        private KennelService CreateKennelService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var kennelService = new KennelService(userId);
            return kennelService;
        }

        //// GET: Kennel
        public async Task<ActionResult> Dashboard()
        {
            KennelService service = CreateKennelService();

            KennelDashboardView mymodel = await service.DisplayKennelDashboardView();

            return View(mymodel);
        }

        //GET
        public async Task<ActionResult> DogDetails([FromUri] int id)
        {
            KennelService service = CreateKennelService();

            KennelDogDetails mymodel = await service.KennelDogDetailsByDogVisitId(id);

            return View(mymodel);
        }

        //GET
        public async Task<ActionResult> CheckIn([FromUri] int id)
        {
            KennelService service = CreateKennelService();

            DogBasic mymodel = await service.GetDogBasicByDogVisitId(id);

            return View(mymodel);
        }

        //POST
        [System.Web.Mvc.HttpPost]
        [System.Web.Mvc.ActionName("CheckIn")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CheckIn([FromUri] int id, string blank)
        {
            KennelService service = CreateKennelService();

            if (await service.CheckInDogVisitById(id))
            {
                return RedirectToAction($"Dashboard");
            };

            ModelState.AddModelError("", "Dog could not be checked-in");

            DogBasic model = await service.GetDogBasicByDogVisitId(id);

            return View(model);
        }

        //GET
        public async Task<ActionResult> CheckOut([FromUri] int id)
        {
            KennelService service = CreateKennelService();

            DogBasic mymodel = await service.GetDogBasicByDogVisitId(id);

            return View(mymodel);
        }

        //POST
        [System.Web.Mvc.HttpPost]
        [System.Web.Mvc.ActionName("CheckOut")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CheckOut([FromUri] int id, string blank)
        {
            KennelService service = CreateKennelService();

            if (await service.CheckOutDogVisitById(id))
            {
                return RedirectToAction($"Dashboard");
            };

            ModelState.AddModelError("", "Dog could not be checked-out");

            DogBasic model = await service.GetDogBasicByDogVisitId(id);

            return View(model);
        }

        //action that does not load a page, returns to dashboard
        public async Task<ActionResult> ResetVisit([FromUri] int id)
        {
            KennelService service = CreateKennelService();

            if (await service.ResetDogVisitById(id))
            {
                return RedirectToAction("Dashboard");
            };

            return View();
        }

        //GET
        public async Task<ActionResult> MorningMealsAndMeds()
        {
            KennelService service = CreateKennelService();

            var mymodel = await service.AllMorningMealsAndMeds();

            return View(mymodel);
        }

        //GET
        public async Task<ActionResult> EveningMealsAndMeds()
        {
            KennelService service = CreateKennelService();

            var mymodel = await service.AllEveningMealsAndMeds();

            return View(mymodel);
        }

        //public async Task<ActionResult> Details(int id)
        //{
        //    KennelService service = CreateKennelService();

        //    KennelDetails mymodel = await service.GetKennelById(id);

        //    return View(mymodel);
        //}

        ////Add method here VVVV
        ////GET
        //public async Task<ActionResult> Delete(int id)
        //{
        //    KennelService infoService = CreateKennelService();

        //    var model = await infoService.GetKennelById(id);
        //    return View(model);
        //}

        //[System.Web.Mvc.HttpPost]
        //[System.Web.Mvc.ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteKennel(int id)
        //{

        //    var service = CreateKennelService();

        //    KennelService infoService = CreateKennelService();
        //    if (await infoService.DeleteKennel(id))
        //    {
        //        return RedirectToAction("Index", "Kennel");
        //    };

        //    ModelState.AddModelError("", "Food could not be deleted.");

        //    return await Delete(id);
        //}
    }
}

KennelCheckin.MVC/Views/Kennel/CheckIn.cshtml
@model KennelData.Data.DogBasic

@{
    ViewBag.Title = "CheckIn";
}

<h2>Check In @Html.DisplayFor(model => model.DogName, new { htmlAttributes = new { @class = "form-control" } })?</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Check In" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Dashboard")
</div>

KennelCheckin.MVC/Views/Kennel/CheckOut.cshtml
@model KennelData.Data.DogBasic

@{
    ViewBag.Title = "CheckOut";
}

<h2>Check-Out @Html.DisplayFor(model => model.DogName, new { htmlAttributes = new { @class = "form-control" } })?</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Check Out" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Dashboard")
</div>

KennelCheckin.MVC/Views/Kennel/Dashboard.cshtml
@model Kennel.Models.Data.Kennel.KennelDashboardItems.KennelDashboardView
@{
    ViewBag.Title = "Dashboard";
}

<div class="jumbotron bg-kennelYellow">
    <h1>Dashboard</h1>
    <p>@Html.ActionLink("Morning Meals and Medications", "MorningMealsAndMeds", "Kennel", null, new { @class = "btn btn-danger" }) 
    @Html.ActionLink("Evening Meals and Medications", "EveningMealsAndMeds", "Kennel", null, new { @class = "btn btn-danger" })</p>
</div>


<table class="table table-striped">
    <h1>
        Dogs On Site Currently
    </h1>
    <thead>
        <tr>
            <th scope="col">Dog Name</th>
            <th scope="col">Visit Notes</th>
            <th scope="col">Special Instructions</th>
            <th scope="col">Allergies</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.DogsOnSite.Count(); i++)
        {
        <tr class="info-row-dog bg-kennelYellow">
            <td class="col-md-2">
                <p>@Html.DisplayFor(model => model.DogsOnSite.ElementAt(i).DogName)</p>
            </td>
            <td class="col-md-2">
                @if (Model.DogsOnSite.ElementAt(i).VisitNotes != null)
                {
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-danger bg-kennelGreen" data-toggle="modal" data-target="#@($"OnSiteNote{i}")">
                    View
                </button>

                <!-- Modal -->
                <div class="modal fade" id="@($"OnSiteNote{i}")" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Notes</h5>
                            </div>
                            <div class="modal-body">
                                @Html.DisplayFor(model => model.DogsOnSite.ElementAt(i).VisitNotes)
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-danger bg-kennelGreen" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                }
            </td>
            <td class="col-md-2">
                @if (Model.DogsOnSite.ElementAt(i).SpecialInstructions != null)
                {
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger bg-kennelGreen" data-toggle="modal" data-target="#@($"OnSiteSpecial{i}")">
                        View
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="@($"OnSiteSpecial{i}")" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Special Instructions</h5>
                                </div>
                                <div class="modal-body">
                                    @Html.DisplayFor(model => model.DogsOnSite.ElementAt(i).SpecialInstructions)
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger bg-kennelGreen" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                </td>
            <td class="col-md-2">
                @if (Model.DogsOnSite.ElementAt(i).Allergies != null)
                {
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger bg-kennelGreen" data-toggle="modal" data-target="#@($"OnSiteAllergies{i}")">
                        View
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="@($"OnSiteAllergies{i}")" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Allergies</h5>
                                </div>
                                <div class="modal-body">
                                    @Html.DisplayFor(model => model.DogsOnSite.ElementAt(i).Allergies)
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger bg-kennelGreen" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                </td>
            <td class="col-md-3">
                @Html.ActionLink("Dog Details", "DogDetails", "Kennel", new { id = Model.DogsOnSite.ElementAt(i).DogVisitId }, new { @class = "btn btn-danger" })
                @Html.ActionLink("Check-out Early", "CheckOut", "Kennel", new { id = Model.DogsOnSite.ElementAt(i).DogVisitId }, new { @class = "btn btn-danger" })
            </td>
        </tr>
        }
    </tbody>
</table>

<table class="table table-striped">
    <h1>
        Dogs Incoming Today
    </h1>
    <thead>
        <tr>
            <th scope="col">Dog Name</th>
            <th scope="col">Visit Notes</th>
            <th scope="col">Special Instructions</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.IncomingDogs.Count(); i++)
        {
            <tr class="info-row-dog bg-kennelYellow">
                <td class="col-md-3">
                    <p>@Html.DisplayFor(model => model.IncomingDogs.ElementAt(i).DogName)</p>
                </td>
                <td class="col-md-3">
                    @if (Model.IncomingDogs.ElementAt(i).VisitNotes != null)
                    {
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-danger bg-kennelGreen" data-toggle="modal" data-target="#@($"IncomingNote{i}")">
                            View
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="@($"IncomingNote{i}")" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Notes</h5>
                                    </div>
                                    <div class="modal-body">
                                        @Html.DisplayFor(model => model.IncomingDogs.ElementAt(i).VisitNotes)
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger bg-kennelGreen" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </td>
                <td class="col-md-3">
                    @if (Model.IncomingDogs.ElementAt(i).SpecialInstructions != null)
                    {
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-danger bg-kennelGreen" data-toggle="modal" data-target="#@($"IncomingSpecial{i}")">
                            View
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="@($"IncomingSpecial{i}")" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Special Instructions</h5>
                                    </div>
                                    <div class="modal-body">
                                        @Html.DisplayFor(model => model.IncomingDogs.ElementAt(i).SpecialInstructions)
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger bg-kennelGreen" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </td>
                <td class="col-md-3">
                    @Html.ActionLink("Dog Details", "DogDetails", "Kennel", new { id = Model.IncomingDogs.ElementAt(i).DogVisitId }, new { @class = "btn btn-danger" })
                    @Html.ActionLink("Check-In", "CheckIn", "Kennel", new { id = Model.IncomingDogs.ElementAt(i).DogVisitId }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>

<table class="table table-striped">
    <h1>
        Dogs Checking Out
    </h1>
    <thead>
        <tr>
            <th scope="col">Dog Name</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.OutgoingDogs.Count(); i++)
        {
            <tr class="info-row-dog bg-kennelYellow">
                <td class="col-md-9">
                    <p>@Html.DisplayFor(model => model.OutgoingDogs.ElementAt(i).DogName)</p>
                </td>

                <td class="col-md-3">
                    @Html.ActionLink("Check-out", "CheckOut", "Kennel", new { id = Model.OutgoingDogs.ElementAt(i).DogVisitId }, new { @class = "btn btn-danger" })
                    @Html.ActionLink("Change Pickup", "ChangePickup", "DogVisit", new { id = Model.OutgoingDogs.ElementAt(i).DogVisitId }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>

KennelCheckin.MVC/Views/Kennel/EveningMealsAndMeds.cshtml
@model IEnumerable<Kennel.Models.Data.Kennel.MealsAndMedications.MealsAndMeds>

@{
    ViewBag.Title = "EveningMealsAndMeds";
}

<h2>Evening Meals And Medications</h2>


<p>
    @Html.ActionLink("Back to Dashboard", "Dashboard")
</p>

@for (int i = 0; i < Model.Count(); i++)
{
    <div class="shadow-lg p-3 mb-5 bg-white rounded">
        <table class="table">
            <thead>
                <tr>
                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.DogBasic.DogName)</th>
                    <td class="col-md-2">@Html.DisplayFor(model => model.ElementAt(i).DogBasic.DogName)</td>
                    <td class="col-md-8"></td>
                </tr>
                @if (Model.ElementAt(i).Food.FoodId == 0)
                {
                    <tr>
                        <th>Fed in the Morning</th>
                    </tr>
                }
                else
                {
                    <tr>
                        <th scope="row" class="col-md-1">Food</th>
                        <td class="col-md-6">@Html.DisplayFor(model => model.ElementAt(i).Food.Name) ( @Html.DisplayFor(model => model.ElementAt(i).Food.AmountPerMeal) ) Cups </td>
                    </tr>
                }
            </thead>
            <tbody>
                @if (Model.ElementAt(i).MedicationList.Count() == 0)
                {
            <th>
                <h4>No Medications</h4>
            </th>
                }
                else
                {
                    for (int c = 0; c < Model.ElementAt(i).MedicationList.Count(); c++)
                    {
                    <table class="table">
                        <thead>
                            <tr>
                                <td></td>
                            </tr>
                            <tr>
                                <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.MedicationList.ElementAt(i).Name)</th>
                                <th class="col-md-2">@Html.DisplayFor(model => model.ElementAt(i).MedicationList.ElementAt(c).Name)</th>
                                <td class="col-md-8">
                                </td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.MedicationList.ElementAt(i).Dose)</th>
                                <td class="col-md-2">@Html.DisplayFor(model => model.ElementAt(i).MedicationList.ElementAt(c).Dose)</td>
                                <td class="col-md-8"></td>
                            </tr>
                            <tr>
                                <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.MedicationList.ElementAt(i).Instructions)</th>
                                <td class="col-md-2">@Html.DisplayFor(model => model.ElementAt(i).MedicationList.ElementAt(c).Instructions)</td>
                                <td class="col-md-8"></td>
                            </tr>
                        </tbody>
                    </table>
                }
            }
            </tbody>
        </table>
    </div>
}

<p>
    @Html.ActionLink("Back to Dashboard", "Dashboard")
</p>

KennelCheckin.MVC/Views/Kennel/MorningMealsAndMeds.cshtml
@model IEnumerable<Kennel.Models.Data.Kennel.MealsAndMedications.MealsAndMeds>

@{
    ViewBag.Title = "MorningMealsAndMeds";
}

<h2>Morning Meals And Medications</h2>


<p>
    @Html.ActionLink("Back to Dashboard", "Dashboard")
</p>

@for (int i = 0; i < Model.Count(); i++)
{
    <div class="shadow-lg p-3 mb-5 bg-white rounded">
        <table class="table">
            <thead>
                <tr>
                    <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.DogBasic.DogName)</th>
                    <td class="col-md-2">@Html.DisplayFor(model => model.ElementAt(i).DogBasic.DogName)</td>
                    <td class="col-md-8"></td>
                </tr>
                @if (Model.ElementAt(i).Food.FoodId == 0)
                {
                    <tr>
                        <th>Fed in the Morning</th>
                    </tr>
                }
                else
                {
                    <tr>
                        <th scope="row" class="col-md-1">Food</th>
                        <td class="col-md-6">@Html.DisplayFor(model => model.ElementAt(i).Food.Name) ( @Html.DisplayFor(model => model.ElementAt(i).Food.AmountPerMeal) ) Cups </td>
                    </tr>
                }
            </thead>
            <tbody>
                @if (Model.ElementAt(i).MedicationList.Count() == 0)
                {
                <th>
                    <h4>No Medications</h4>
                </th>
            }
            else
            {
                for (int c = 0; c < Model.ElementAt(i).MedicationList.Count(); c++)
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <td></td>
                            </tr>
                            <tr>
                                <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.MedicationList.ElementAt(i).Name)</th>
                                <th class="col-md-2">@Html.DisplayFor(model => model.ElementAt(i).MedicationList.ElementAt(c).Name)</th>
                                <td class="col-md-8">
                                </td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.MedicationList.ElementAt(i).Dose)</th>
                                <td class="col-md-2">@Html.DisplayFor(model => model.ElementAt(i).MedicationList.ElementAt(c).Dose)</td>
                                <td class="col-md-8"></td>
                            </tr>
                            <tr>
                                <th scope="row" class="col-md-2">@Html.DisplayNameFor(model => model.MedicationList.ElementAt(i).Instructions)</th>
                                <td class="col-md-2">@Html.DisplayFor(model => model.ElementAt(i).MedicationList.ElementAt(c).Instructions)</td>
                                <td class="col-md-8"></td>
                            </tr>
                        </tbody>
                    </table>
                }
            }
                </tbody>
            </table>
        </div>
    }

<p>
    @Html.ActionLink("Back to Dashboard", "Dashboard")
</p>

KennelCheckin.MVC/Views/Kennel/ResetVisit.cshtml
@{
    ViewBag.Title = "ResetVisit";
}

<h2>This could not be reset! Please try again!</h2>

<div>
    @Html.ActionLink("Back to List", "Dashboard")
</div>